image: 161.189.41.29:8082/sros/native:latest

before_script:
  - >
    if [ ! -d "../sros-file-transmit" ]; then
      git clone http://gitlab+deploy-token-7:s9VB6FWNz1keFzM25dWo@git.standard-robots.com/SROS/sros-file-transmit.git ../sros-file-transmit
    fi

variables:
  GIT_SUBMODULE_STRATEGY: recursive # 初始化自仓库

toradex-release:
  type: build
  script:
    - cd update
    - ./one.sh release
    - source ../version.sh
    - cd ../cfg/sros-resources && git checkout . && cd -
  cache:
    key: one-key-to-rule-them-all
    paths:
      - build-toradex
      - build-native
      - core/proto/main.pb.cc
      - core/proto/main.pb.h
      - core/proto/monitor.pb.cc
      - core/proto/monitor.pb.h
      - core/version.h
  artifacts:
    name: "$(cd update && ls SROS-v*)"
    paths:
      - update/SROS-v*.update
    expire_in: 1 week

native-test:
  stage: test
  script:
    - cd update
    - ./one.sh test