@startuml
legend top left
绿色部分表示被监控的，黄色部分表示没被监控，红色表示监控有问题的。
end legend

collections 定位模块
collections SDK
collections SROS
collections 操作系统
collections SRC

activate SRC  #Green
操作系统 <[#green]- SRC: 定时10ms上传pose
activate 操作系统  #Yellow
note over 操作系统
串口到操作系统
时间和SROS响应
系统时间没监测
end note
{start} SDK <- 操作系统: 系统将pose上传SDK
deactivate 操作系统
activate SROS #Red

note over SROS #Red
SROS检测到
两次pose
时间超过
100ms
end note
note over SRC #Green
SRC设定100ms上传
之前通过pose的roll
上传SRC检测的两个
pose上传间隔
end note

activate SDK #Green
定位模块 <[#green]- SDK: 将pose上传定位模块
activate 定位模块 #Green
定位模块 -[#green]> SDK: 将融合的位置发给SDK
deactivate 定位模块
SDK -[#green]> 操作系统:
deactivate SDK
activate 操作系统 #Yellow
note over 操作系统
操作系统
将数据发
到串口时间
没监测
end note
操作系统 -[#green]> SRC
deactivate 操作系统


操作系统 <[#green]- SRC: 第二帧pose
deactivate SRC
activate 操作系统 #Yellow
{start} SDK <- 操作系统: 系统将pose上传SDK
deactivate 操作系统
deactivate SROS
activate SDK #Green
定位模块 <[#green]- SDK: 将pose上传定位模块
activate 定位模块 #Green
定位模块 -[#green]> SDK: 将融合的位置发给SDK
deactivate 定位模块
SDK -[#green]> 操作系统:
deactivate SDK
activate 操作系统 #Yellow
操作系统 -[#green]> SRC
deactivate 操作系统
@enduml